p8105_hw2_jl5934
================
Jesus Luevano
2023-09-26

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Problem 1

\##Importing the Data, cleaning it

Start with the polls data by month and year.

``` r
Pol_Month.df = read_csv("data/fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(
    mon,
    c("year", "month", "day")
  ) 
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
Pol_Month.df = Pol_Month.df %>% mutate(month = case_match(
    month,
    "01" ~ "January",
    "02" ~ "February",
    "03" ~ "March",
    "04" ~ "April",
    "05" ~ "May",
    "06" ~ "June",
    "07" ~ "July",
    "08" ~ "August",
    "09" ~ "September",
    "10" ~ "October",
    "11" ~ "November",
    "12" ~ "December"))

Pol_Month.df = Pol_Month.df %>% mutate(President = case_when(
  prez_gop == 1 ~ "gop",
  prez_dem == 1 ~ "dem"
))
  
Pol_Month.df = select(Pol_Month.df, -c("prez_gop", "prez_dem", "day"))
```

Next do the Snp outcome, again by month and year. Here, the years were
in the format of only the last two digits (as opposed to four digits
like the other datasets). I saw that 00-13 related to 2000-2013, and
50-99 for 1950-1999. So I added a new column to create a prefix that I
then concatenated to make the full four digit variable, and then removed
that prior working column. This was to allow for downstream merging by
year and month.

``` r
Snp.df = read_csv("data/fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  separate(
    date,
    c("month", "day", "year")
  )
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
Snp.df = Snp.df %>% mutate(month = case_match(
    month,
    "1" ~ "January",
    "2" ~ "February",
    "3" ~ "March",
    "4" ~ "April",
    "5" ~ "May",
    "6" ~ "June",
    "7" ~ "July",
    "8" ~ "August",
    "9" ~ "September",
    "10" ~ "October",
    "11" ~ "November",
    "12" ~ "December"))

Snp.df = select(Snp.df, c(year, month, everything()))

Snp.df <- Snp.df %>%
  mutate(year_prefix = case_when(
    year < 16 ~ 20,
    year > 49 ~ 19)) %>%
  mutate(year = paste(year_prefix,year, sep = "")) %>%
  select(-c("year_prefix"))
```

Last the unemployment rate by month and year. Here month information was
by three letter abbreviation, so converted that. Additionally, year was
in format of number, other two were character format, so I converted to
allow for downstream merging.

``` r
Unemployment.df = read_csv("data/fivethirtyeight_datasets/unemployment.csv") %>%
  janitor::clean_names() %>%
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment_rate"
  )
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
Unemployment.df[["year"]] <- as.character(Unemployment.df[["year"]])

Unemployment.df = Unemployment.df %>% mutate(month = case_match(
    month,
    "jan" ~ "January",
    "feb" ~ "February",
    "mar" ~ "March",
    "apr" ~ "April",
    "may" ~ "May",
    "jun" ~ "June",
    "jul" ~ "July",
    "aug" ~ "August",
    "sep" ~ "September",
    "oct" ~ "October",
    "nov" ~ "November",
    "dec" ~ "December"))
```

## Merging the datasets

First we merge Pol data by month and snapshot based on same column of
year and month. Then we take that new merged dataframe and merge it with
unemployment again by year and month.

``` r
Pol_Snp.df <- full_join(Pol_Month.df, Snp.df, by = c("year", "month"))

Pol_Snp_Unemployment.df <- full_join(Pol_Snp.df, Unemployment.df, by = c("year", "month"))
```

## Describing the dataframes

Variables contained:

- The Pol_Month dataframe included variables for year, month, gov_gop,
  sen_gop, rep_gop, gov_dem, sen_dem, rep_dem, President. The size of
  the dataset is 822 rows by 9 columns. It was describing the breakdown
  of seats in the senate, governorships, and the President based on
  Democrat or Republican status for specific date that was made up of a
  day, month, and year.

  - The range of years represented in this dataset are 1947, 2015.

- The Snp dataframe included variables year, month, day, close. The size
  of the dataset is 787 rows by 4 columns. It was describing the Snp
  close value, based on date that included day, month, and year.

  - The range of years represented in this dataset are 1950, 2015. The
    range of the Snp was 17.049999, 2107.389893, and the mean was
    474.8887404.

- The Unemployment dataframe included variables year, month,
  unemployment_rate. The size of the dataset is 816 rows by 3 columns.
  It was describing the unemployment rate based on date that inclued
  month and year.

  - The range of years represented in this dataset are 1948, 2015. The
    range of the Unemployment rate was NA, NA, and the mean was NA.
